config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

	resources :something

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/something.rb
class Something < ApplicationRecord
	self.table_name = 'something'

	CITY_LIST = ["Houston", "Los Angeles"]

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/something_controller.rb
class SomethingController < ApplicationController

	def show

		if Rails.env == "development"
			unless @record
				@record = ActiveRecord::Base.connection.execute("
					SELECT * FROM something WHERE city = '#{params["id"]}' AND category = '#{params["category"]}'
				")
			end
		else
			unless @record
				@record = ActiveRecord::Base.connection.execute("
					SELECT * FROM output_revised_v2 WHERE city = '#{params["id"]}' AND category = '#{params["category"]}'
					")
			end
		end

	end

	def new
		@record = Something.new
	end

	def create

		if Rails.env == "development"
			@record = ActiveRecord::Base.connection.execute("
					SELECT * FROM something WHERE city = '#{something_params["city"]}' AND category = '#{something_params["category"]}'
				")
		else
			@record = ActiveRecord::Base.connection.execute("
					SELECT * FROM output_revised_v2
					WHERE city = '#{something_params["city"]}'
					AND category = '#{something_params["category"]}'
				")
		end

		redirect_to something_path(id: @record.first["city"], category: @record.first["category"])

	end


	private

  def something_params

    params[:something].permit(:city, :category)

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Team92</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
      
    <!-- <script type="text/javascript" src="https://d3js.org/d3.v3.min.js"></script> -->
    <script type="text/javascript" src="http://d3js.org/topojson.v1.min.js"></script>
    <!-- <script type="text/javascript" src="http://d3js.org/queue.v1.min.js"></script> -->
    <!-- <script type="text/javascript" src="http://d3js.org/d3.tip.v0.6.3.js"></script> -->

    <script src="https://cdnjs.cloudflare.com/ajax/libs/d3/4.2.2/d3.min.js"></script>

    <link rel="shortcut icon" href="#" />
    <style type="text/css">
        .title {
            position: absolute;
            top: 5%;
        }
        .button {
            /*position: absolute;*/
            top: 75%;
            left: 85%;
        }
        .d3-tip {
            background: rgb(255, 128, 128, 0.8);
            color: white;
            font-size: 14px;
            font-weight: bold;
            padding: 8px;
        }
    </style>

    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= yield %>
    
  </body>
</html>

app/views/something/new.html.erb
<div class="container-fluid" style="margin-left: 5%; margin-top: 5%">
	<div class="row">
		<div class="col-sm-4">
			<%= form_for @record, url: {action: "create"} do |f| %>
				<div>
					<%= f.label :'Choose your city', {style: "margin-right: 8%; margin-top: 8%; margin-left: 12%;"}%>
					<%#= f.select :city, [ 'Atlanta','Boston','Chicago', 'Cleveland', 'Dallas', 'Denver', 'Detroit', 'Houston', 'Los Angeles', 'Miami', 'Minneapolis', 'New York', 'Orlando', 'Phoenix', 'Philadelphis', 'Portland', 'San Diego', 'San Francisco', 'Seattle', 'Washington'], :prompt => 'Select One' %>
					<%= f.select :city, [ 'Cleveland', 'Phoenix'], :prompt => 'Select One' %>
				</div>
				<div style="margin-top: 1%">
					<%= f.label :'Choose your category', {style: "margin-left: 12%; margin-right: 0.2%"} %>
					<%#= f.select :category, ['American', 'Arabian', 'Argentine', 'Barbeque', 'Brazilian', 'Breakfast & Brunch', 'British', 'Buffets', 'Burgers', 'Cafeteria', 'Cajun/Creole', 'Cheesesteaks', 'Chinese', 'Delis', 'Diners', 'Fast Food', 'Food Court', 'French', 'German', 'Gluten-Free', 'Hawaiian', 'Hot Dogs', 'Hot Pot', 'Indian', 'Italian', 'Japanese', 'Korean', 'Mediterranean', 'Mexican', 'Mongolian', 'Pizza', 'Russian', 'Seafood', 'Spanish', 'Steakhouses', 'Sushi Bars', 'Thai', 'Vegetarian', 'Vietnamese', 'Waffles', 'Wraps'], :prompt => 'Select One' %>
					<%= f.select :category, ['American', 'Breakfast', 'Chinese', 'Italian','Mexican', 'Nightlife'], :prompt => 'Select One' %>
				</div>
				<div style="margin-top: 5%">
					<%= f.submit "Create", {:class=>"btn btn-outline-dark", style: "width: 50%; margin-left: 15%;"} %>
					<%#= f.submit "Start over", {:class=>"btn btn-outline-primary", style: "width: 25%; margin-left: 8%;"}%>
				</div>
				<img src="<%= asset_path 'welcome.jpg' %>" style="width: 90%; margin-top: 20%; margin-left: 5%;">
			<% end %>
		</div>
		<div class="col-sm-8" id='map'>

		</div>
		<div class="col-sm-1"></div>
	</div>
</div>

<script type="text/javascript">
	var w = 960,
		h = 500,
		h_rect = h/20,
		margins = {top: 0, bottom: 0, left: 0, right: 0};
	var map = d3.select('#map')
				.append('svg')
				.attr('width', w)
				.attr('height', h)
				.append('g')
				.attr('transform', 'translate(' + margins.left + ',' + margins.top + ')');
	var projection = d3.geoAlbersUsa()
						.translate([w/2, h/2])
						.scale(1000);
	var path = d3.geoPath()
				.projection(projection);

	d3.json("<%= asset_path 'us.json' %>", function(error, us){
		if (error) throw error;
		// console.log(us);
		map.append('g')
			.attr('class', 'counties')
			.selectAll('path')
			.data(topojson.feature(us, us.objects.counties).features)
			.enter()
			.append('path')
			.attr('d', path)
			.style('fill', '#F1948A');

		map.append('path')
			.attr('class', 'state-borders')
			.datum(topojson.mesh(us, us.objects.states, (a, b) => a !== b))
			.attr('fill', 'none')
			.attr('stroke', '#FADBD8')
			.attr('stroke-linejoin', 'round')
			.attr('d', path);
	});
</script>

app/views/something/show.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="title" style="margin-left: 20%; font-size: 22px; font-weight: bolder;">
			<%= @record.first["category"] %> Restaurants in <%= @record.first["city"] %>
			<% @record.each do |rec| %>
				<%#= rec["pos_rev"] %>
				<%#= JSON.parse(rec["neg_rev"]).keys.first(3) %>
			<% end %>
		</div>
	</div>
	<div class="row">
		<div id='map' style="margin-left: 20%; margin-top: 3%;"></div>
	</div>
	<div class="row">
		<div class="col"></div>
		<div class="col-md-3">
			<div class="button">
				<%= link_to "Start Over", new_something_path, {:class=>"btn btn-outline-primary button", style: "width: 40%;"} %>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">

	var popByZip = {},
		posByZip = {},
		negByZip = {};

	<% @record.each do |rec| %>
		popByZip[<%= rec["zip"] %>] = (<%= rec["pop_score"].nil? ? -999 : rec["pop_score"] %>).toFixed(2)
		if (popByZip[<%= rec["zip"] %>] == -999.00) {
		   popByZip[<%= rec["zip"] %>] = "Data Not Available"
		}
		posByZip[<%= rec["zip"] %>] = Object.keys(JSON.parse("<%= rec["pos_rev"] %>".replace(/&quot;/g,'"'))).slice(0,3)
		negByZip[<%= rec["zip"] %>] = Object.keys(JSON.parse("<%= rec["neg_rev"] %>".replace(/&quot;/g,'"'))).slice(0,3)
	<% end %>;


	var w = 800,
		h = 600,
		h_rect = h/20,
		margins = {top: 0, bottom: 0, left: 0, right: 0};

	var map = d3.select('#map')
				.append('svg')
				.attr('width', w)
				.attr('height', h)
				.attr('transform', 'translate(' + margins.left + ',' + margins.top + ')');

	var city = "<%= @record.first["city"] %>";

	if (city == 'Cleveland'){
		features = Cleveland_json.features;
		rotate = [81.7, 0];
		center = [0, 41.4];
		scale = 80000;
		translate = [w*0.6,h*0.6];
		pins = Cleveland_pins_json.features;
	} else if (city == 'Phoenix') {
		features = Phoenix_json.features;
		rotate = [111, 0];
		center = [0, 33];
		scale = 65000;
		translate = [w * 1.9 ,h * 1.5];
		pins = Phoenix_pins_json.features;
	}

	var g = map.append('g');

	var albersProjection = d3.geoAlbers()
							  .scale(scale)
							  .rotate(rotate)
							  .center(center)
							  .translate(translate);

	var geoPath = d3.geoPath()
    				.projection(albersProjection);

    g.selectAll( "path" )
	  .data(features)
	  .enter()
	  .append( "path" )
	  .attr( "fill", "#46C7C7" )
	  .attr( "d", geoPath );

	var tip = d3.tip()
				.attr('class', 'd3-tip')
				.offset([-10, 10])
				.direction('n')
				.html(function(d){
					return ('Zipcode: ' + d.zip + '<br/>Category: ' + "<%= @record.first["category"] %>" + '<br/>Popularity Score: ' + popByZip[d.zip] + '<br/>Top three posivite key words: ' + posByZip[d.zip]) + '<br/>Top three negavite key words: ' + negByZip[d.zip];
				});
	map.call(tip);

	var g_pins = map.append('g');

	g_pins.selectAll( "path" )
		  .data(pins)
		  .enter()
		  .append( "path" )
		  .attr( "d", geoPath )
		  .attr('fill', '#800000')
		  .on('mouseover', tip.show)
		  .on('mouseout', tip.hide);

</script>